@php($conference = $conference ?? null)
<div class="grid gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><label class="form-label" for="name">Nama conference</label><input class="form-input" id="name" name="name" value="{{ old('name', $conference?->name) }}" required></div>
    <div><label class="form-label" for="slug">Slug form publik</label><div class="flex items-center rounded-xl border border-navy/15 bg-white focus-within:border-orange focus-within:ring-4 focus-within:ring-orange/10"><span class="pl-4 text-sm text-muted">/</span><input class="min-h-12 min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" id="slug" name="slug" value="{{ old('slug', $conference?->slug) }}" required></div></div>
    <div><label class="form-label" for="status">Status</label><select class="form-input" id="status" name="status">@foreach (\App\Enums\ConferenceStatus::cases() as $status)<option value="{{ $status->value }}" @selected(old('status', $conference?->status?->value ?? 'draft') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
    <div class="md:col-span-2"><label class="form-label" for="description">Deskripsi</label><textarea class="form-input min-h-28 py-3" id="description" name="description">{{ old('description', $conference?->description) }}</textarea></div>
    <div><label class="form-label" for="timezone">Zona waktu</label><input class="form-input" id="timezone" name="timezone" value="{{ old('timezone', $conference?->timezone ?? 'Asia/Jakarta') }}" required></div>
    <div><label class="form-label" for="starts_at">Tanggal mulai</label><input class="form-input" id="starts_at" type="datetime-local" name="starts_at" value="{{ old('starts_at', $conference?->starts_at?->format('Y-m-d\TH:i')) }}"></div>
    <div><label class="form-label" for="ends_at">Tanggal selesai</label><input class="form-input" id="ends_at" type="datetime-local" name="ends_at" value="{{ old('ends_at', $conference?->ends_at?->format('Y-m-d\TH:i')) }}"></div>
    <div><label class="form-label" for="submission_opens_at">Submission dibuka</label><input class="form-input" id="submission_opens_at" type="datetime-local" name="submission_opens_at" value="{{ old('submission_opens_at', $conference?->submission_opens_at?->format('Y-m-d\TH:i')) }}"></div>
    <div><label class="form-label" for="submission_closes_at">Submission ditutup</label><input class="form-input" id="submission_closes_at" type="datetime-local" name="submission_closes_at" value="{{ old('submission_closes_at', $conference?->submission_closes_at?->format('Y-m-d\TH:i')) }}"></div>
</div>
